    /**
     * test that Error types (BoolErrRecord) are supported properly.
     * @see testBool
     */
    @Test
    public void testErr() throws IOException {

        Workbook wb1 = _testDataProvider.createWorkbook();
        Sheet s = wb1.createSheet("testSheet1");
        Row r;
        Cell c;

        // B1
        r = s.createRow(1);
        c=r.createCell(1);
        assumeTrue(0 == c.getRowIndex());
        assumeTrue(1 == c.getColumnIndex());
        c.setCellErrorValue(FormulaError.NULL.getCode());

        // C1
        c=r.createCell(2);
        assumeTrue(0 == c.getRowIndex());
        assumeTrue(2 == c.getColumnIndex());
        c.setCellErrorValue(FormulaError.DIV0.getCode());

        Workbook wb2 = _testDataProvider.writeOutAndReadBack(wb1);
        wb1.close();

        s = wb2.getSheet("testSheet1");

        r = s.getRow(0);
        assumeTrue("Row 1 should have 2 cells", 2 == r.getPhysicalNumberOfCells());

        c = r.getCell(1);
        assertEquals(Cell.CELL_TYPE_ERROR, c.getCellType());
        assertEquals("B2 value == #NULL!", FormulaError.NULL.getCode(), c.getErrorCellValue());

        c = r.getCell(2);
        assertEquals(Cell.CELL_TYPE_ERROR, c.getCellType());
        assertEquals("C2 value == #DIV/0!", FormulaError.DIV0.getCode(), c.getErrorCellValue());

        wb2.close();
    }

