    /**
     * Bug 37684  : Unhandled Continue Record Error
     */
    public void test37684 () throws Exception {
        FileInputStream in = new FileInputStream(new File(cwd, "37684-1.xls"));
        HSSFWorkbook wb = new HSSFWorkbook(in);
        in.close();

        assertTrue("No exceptions while reading workbook", true);

        //serialize and read again
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        wb.write(out);
        out.close();
        assertTrue("No exceptions while saving workbook", true);

        wb = new HSSFWorkbook(new ByteArrayInputStream(out.toByteArray()));
        assertTrue("No exceptions while reading saved stream", true);


        in = new FileInputStream(new File(cwd, "37684-2.xls"));
        wb = new HSSFWorkbook(in);
        in.close();

        assertTrue("No exceptions while reading workbook", true);

        //serialize and read again
        out = new ByteArrayOutputStream();
        wb.write(out);
        out.close();
        assertTrue("No exceptions while saving workbook", true);

        wb = new HSSFWorkbook(new ByteArrayInputStream(out.toByteArray()));
        assertTrue("No exceptions while reading saved stream", true);
    }

