   public void testFileWritable() throws Exception {
       File temp = TempFile.createTempFile("TestDataSource", ".test");
       try {
           writeDataToFile(temp);
       
           FileBackedDataSource ds = new FileBackedDataSource(temp, false);
           try {
               checkDataSource(ds, true);
           } finally {
               ds.close();
           }
           
           // try a second time
           ds = new FileBackedDataSource(temp, false);
           try {
               checkDataSource(ds, true);
           } finally {
               ds.close();
           }

           writeDataToFile(temp);
       } finally {
           assertTrue(temp.exists());
           assertTrue("Could not delete file " + temp, temp.delete());
       }
    }

