    @Test
    public void testRewritableFile() throws Exception {
        File temp = TempFile.createTempFile("TestDataSource", ".test");
        try {
            writeDataToFile(temp);

            FileBackedDataSource ds = new FileBackedDataSource(temp, true);
            try {
                ByteBuffer buf = ds.read(0, 10);
                assertNotNull(buf);
                buf = ds.read(8, 0x400);
                assertNotNull(buf);
            } finally {
                ds.close();
            }

            // try a second time
            ds = new FileBackedDataSource(temp, true);
            try {
                ByteBuffer buf = ds.read(0, 10);
                assertNotNull(buf);
                buf = ds.read(8, 0x400);
                assertNotNull(buf);
            } finally {
                ds.close();
            }

            writeDataToFile(temp);
        } finally {
            assertTrue(temp.exists());
            assertTrue(temp.delete());
        }
    }

